### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by zooloogorbonos** [Gethe/nibRealUI_BossSkins#1]
http://i1.imageban.ru/out/2014/07/11/deef3caf4f4b382d7f3c8602ec976cac.jpg

please correct Russian localization

**Comment by zooloogorbonos** [comment]
and?

**Comment by zooloogorbonos** [comment]
senks!

**Comment by zooloogorbonos** [comment]
stubbornly do not want to refine? Why, then, was to create a place in the writing of the complaints?

**Comment by Gethe** [comment]
Fixed in the next update for 6.1
